### ISSUE TITLE
Radius query always returning empty array

### ISSUE THREAD

**Issue by peterWilson34** [rh389/dynamodb-geo.js#22] opened 2018-05-20 11:09 UTC
I followed the code in the docs of this module and I just wanted to try the simple demo on it,
but when I try to use query radius I always have an empty array
  ```
usersTableManager.queryRadius({
          RadiusInMeter: 10000,
          CenterPoint: {
            latitude: 30.04023579999999,
            longitude: 31.236852,
          }
        }).then(function (data) {

      console.log('Done!')
      console.log(data);
    },function (err) {
      console.log(err);
    });
```
I tried to insert many records wit different lat,long pairs and I tried to use `config.longitudeFirst = true;` and `config.longitudeFirst = false;`

any help will be appreciated, thanks in advance

**Comment by rh389** [comment] 2018-05-20 12:45
Could you have a look in your database and post one of the records this should be returning? We can check whether something’s gone wrong when inserting.

**Comment by rh389** [comment] 2018-05-30 17:59
I've just tried to reproduce this but it's working fine for me. Just a couple of points:

- Your data has a hash length of 6, which means you'll need `config.hashKeyLength = 6` to get any results
- `config.longitudeFirst` determines the format of the `geoJson` attribute. `geoJson` isn't actually used for querying so this is in practice only relevant for inserts. Your data has the longitude first.

**Comment by rh389** [comment] 2018-06-30 22:52
Closing for now as I can't reproduce, but let me know if you have more info.

**Closed by rh389** 2018-06-30 22:52 UTC
